# Generated by Django 5.0 on 2023-12-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_delete_menuitem_remove_booking_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='id',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
